name: Build and Release VSCode Extension

on:
  release:
    types: [created]
  # TODO: Remove
  pull_request:

permissions:
  contents: write

jobs:
  build-extension:
    name: Build Platform Extension
    strategy:
      matrix:
        include:
          # Windows platforms (cross-compiled on Ubuntu)
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            platform: win32-x64
          # TODO: Re-enable
          # - os: ubuntu-24.04-arm
          #   target: aarch64-pc-windows-gnullvm
          #   platform: win32-arm64

          # Linux platforms
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux-x64
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            platform: linux-arm64

          # macOS platforms
          - os: macos-13
            target: x86_64-apple-darwin
            platform: darwin-x64
          - os: macos-latest
            target: aarch64-apple-darwin
            platform: darwin-arm64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install cross-compilation tools
        if: contains(matrix.target, 'pc-windows-gnu')
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          rustflags: ""

      - name: Build LSP
        run: cargo build --release --target ${{ matrix.target }} -p atopile_lsp

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Prepare LSP binary
        run: |
          mkdir -p vscode/lsp
          ls -la target/
          cp target/${{ matrix.target }}/release/atopile_lsp${{ contains(matrix.target, 'windows') && '.exe' || '' }} vscode/lsp/atopile_lsp${{ contains(matrix.target, 'windows') && '.exe' || '' }}
          ${{ !contains(matrix.target, 'windows') && 'chmod +x vscode/lsp/atopile_lsp' || '' }}

      # Set the version in package.json from a workflow dispatch input
      - name: Pre-release version
        if: github.event_name == 'release' && (github.event.release.prerelease || github.event.release.draft)
        # The pre-release version adds 1000 to the patch version to get around the lack of proper semver support
        # https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions
        run: |
          TAGGED_SEMVER=$(npx semver $(git describe --tags --exact-match HEAD))
          PUBLISH_VERSION="$($TAGGED_SEMVER | cut -d- -f1 | awk -F. '{$NF+=1000;OFS=".";$1=$1}1')"
          npm version --no-git-tag-version $PUBLISH_VERSION

      - name: Release version
        if: github.event_name == 'release' && !github.event.release.prerelease && !github.event.release.draft
        run: npm version --no-git-tag-version $(npx semver $(git describe --tags --exact-match HEAD))

      - name: Install dependencies and build VSIX
        run: |
          npm ci
          VERSION=$(node -p "require('./package.json').version")
          npx --yes vsce package --target ${{ matrix.platform }} --out "atopile-analyzer-$VERSION-${{ matrix.platform }}.vsix"
        working-directory: vscode

      - name: Upload VSIX to Release
        uses: softprops/action-gh-release@v1
        with:
          files: vscode/atopile-analyzer-*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish pre-release to VS Code Marketplace
      #   # if: github.event_name == 'release' && (github.event.release.prerelease || github.event.release.draft)
      #   # Skip duplicate here to allow manual triggering
      #   run: npx vsce publish --skip-duplicate --pre-release -i "atopile-analyzer-*.vsix"
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_PAT }}

      # Enable this once we're happy with it's behavior on v0.3, even if only not producing spurious errors
      # - name: Publish release to VS Code Marketplace
      #   if: github.event_name == 'release' && !github.event.release.prerelease && !github.event.release.draft
      #   # Skip duplicate here to allow manual triggering
      #   run: npx vsce publish --skip-duplicate -i "atopile-analyzer-*.vsix"
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_PAT }}
